# 站点基本信息
title: "Kaixing Cao"
description: "Personal homepage"
site_theme: ""  # dark or light


# sidebar 作者信息
author:
  name: "Kaixing Cao"
  institution: "University of Milan"
  avatar: "/picture/hao.jpeg"


# 导航栏
nav:
  - name: Homepage
    url: /
  - name: Research
    url: /research/

# 社交链接
links:
  - name: Email
    url: mailto:kaixing.cao@unimi.it
    icon: fas fa-envelope
  - name: ORCID
    url: https://orcid.org/0009-0000-6785-8755
    icon: fab fa-orcid
    new_tag: true
  - name: ArXiv
    url: https://arxiv.org/a/0009-0000-6785-8755.html
    icon: ai ai-arxiv
    new_tag: true
  - name: GitHub
    url: https://github.com/kaihsingtsao
    icon: fab fa-github
    new_tag: true

collections:
  pages:
    output: true   # 确保 _pages 下的文件会生成 HTML



  

